### PR TITLE
Closed #8 Set HEADER_SEARCH_PATHS to relative path

### LINKED ISSUE #8: HEADER_SEARCH_PATHS issue
The current HEADER_SEARCH_PATHS is below

```
HEADER_SEARCH_PATHS = /Users/droot/Dropbox/Netrek/Netrek/OpenSSL/include/;
```

Can this be switched to a relative path?

Really don't know Xcode, learning, I'll attempt to submit a PR.

### PR DESCRIPTION
**Pull request by basictheprogram**
Need to learn Xcode. Sorry, messy PR.

### CODE REVIEW

**Comment by basictheprogram** [comment]
Sorry, Xcode newbie, don't now if
```
    compatibilityVersion = "Xcode 10.0"
```
Will break things.

**Comment by basictheprogram** [comment]
@darrellroot the public domain target builds for me after this PR is applied

**Comment by basictheprogram** [comment]
Looks like you added the "$(PROJECT_DIR)/Netrek/OpenSSL/include"; I'll close this PR, I did not know about the $(PROJECT_DIR)

**Comment by darrellroot** [comment]
I appreciate your help getting this buildable for others.  Very annoying if people can’t just “clone and build”.

Darrell

**Pull request closed without merging**
